spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/document_manager
    username: mohanad
    password: yourpassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    org:
      hibernate:
        SQL=DEBUG: